FROM golang:1.19-alpine

WORKDIR /

RUN apk add --no-cache ca-certificates curl bash

RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-arm64.tar.gz | tar xvz

RUN ln -s /migrate /usr/local/bin/migrate

ENTRYPOINT [ "migrate" ]
CMD [ "--help" ]